### ISSUE TITLE
Release to maven central

### ISSUE THREAD

**Issue by onsails** [johannburkard/UUID#1]
Would be great to have this library published to maven central (or to sonatype which synchronizes with maven central itself) to let other libraries easily depend on this project and not worry about putting extra resolver to pom.xml.
Another problem with `eaio.com/maven2` that it does not work for some users in China, lots of developers from China reported it in [our project](https://github.com/actorapp/actor-platform).

**Comment by johannburkard** [comment]
The new repository location is repo.eaio.com/maven2. And yes, it's a Maven 2 repository, just with directory browsing disabled.

I'll see what I can do about the central release when there's a need to release a new version.

**Comment by Tvaroh** [comment]
+1 for publishing to Maven Central. Thanks for great work!
