### ISSUE TITLE
Latest UUID does not seem to be on Maven Central…

### ISSUE THREAD

**Issue by victornoel** [johannburkard/UUID#2]
Hi,

Apparently only version 3.2 is on maven central, could it be possible to also upload the latest version?

**Comment by johannburkard** [comment]
I can't, can you?

**Comment by victornoel** [comment]
I can help you setup it, but you will have to take care of it because it involves having credentials for sonatype OSS.

**Comment by victornoel** [comment]
Here is the easiest way to do it: http://central.sonatype.org/pages/ossrh-guide.html

If you have questions I can help you to configure things :)

**Comment by johannburkard** [comment]
Thanks @victornoel, I may come back to you on this in the next couple of weeks.

**Comment by johannburkard** [comment]
Don't think it'll ever be on Maven Central TBH. Too many things to do...

**Comment by johannburkard** [comment]
Probably not going to happen by myself unless someone jumps in.
