### ISSUE TITLE
Unconditional use of Math.random() in generation of clockSeqAndNode

### ISSUE THREAD

**Issue by mrubin** [johannburkard/UUID#4]
Please see this line: https://github.com/johannburkard/UUID/blob/master/src/main/java/com/eaio/uuid/UUIDGen.java#L194

Either this line is incorrect, or the comment above it is incorrect. The comment says:

```
// Skip the clock sequence generation process and use random instead.
```

But we're not skipping the clock sequence generation... we do that sequence and then we unconditionally add in the bits from this random call.

**Comment by johannburkard** [comment]
Good catch. Sorry, didn't see your bugs earlier, not sure why.

**Comment by johannburkard** [comment]
I think this comment is correct. The spec asks for a consecutive (AKA persistent) clock sequence to be added to the last 16 bits. Since UUID does not use persistent storage, I just use Math.random().

Just don't ask me why I'm using x3FFF and not x3F.
