### ISSUE TITLE
JDK 11 compatibility

### ISSUE THREAD

**Issue by danwashusen** [johannburkard/UUID#6]
JDK11 has removed CORBA (see https://openjdk.java.net/jeps/320). To avoid java.lang.NoClassDefFoundError errors at runtime references to IDLEntity need to removed.

**Comment by johannburkard** [comment]
Thanks for the report, are you currently working on a patch?

**Comment by danwashusen** [comment]
Yep, just submitted a pull request that removes the CORBA references...

**Comment by johannburkard** [comment]
I'll integrate this some time 2019...

**Comment by pnyheim** [comment]
Any ETA on this fix?

**Comment by johannburkard** [comment]
Good question. As you can see, it's not going too fast. The thing is I have a billion other things to do and I'm not doing a lot of software development ATM. I'll try though.

**Comment by pnyheim** [comment]
I fully appreciate that you are busy with other things, and that you may have moved on from developing this. This is a simple enough library to fork and build our own release of, so we might just do that while waiting for an "official" release to maven central from you. 

Thank you for your prompt reply.
Paul

**Comment by johannburkard** [comment]
Fixed with 97c0440bcec6092d65591090d32daa89c6ca4640.
